# Generated by Django 4.2.2 on 2023-07-08 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0002_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='loginid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
