# Generated by Django 4.2.2 on 2023-07-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0003_artist_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(default='Not Paid', max_length=100),
        ),
    ]
