# Generated by Django 4.2.2 on 2023-07-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0005_remove_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='regDate',
            field=models.DateField(null=True),
        ),
    ]
