# Generated by Django 4.2.2 on 2023-07-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0006_login_regdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
