# Generated by Django 4.2.2 on 2023-07-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0007_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='artistId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.artist'),
        ),
    ]
