# Generated by Django 4.2.2 on 2023-07-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='InCart', max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.user')),
            ],
        ),
    ]
