# Generated by Django 4.2.2 on 2023-07-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
