# Generated by Django 4.2.2 on 2023-07-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0011_cart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.user')),
            ],
        ),
    ]
