# Generated by Django 4.2.2 on 2023-07-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0012_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.cart')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.user')),
            ],
        ),
    ]
