# Generated by Django 5.0.1 on 2024-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0017_alter_artist_address_alter_artist_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tripday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
