# Generated by Django 5.0.1 on 2024-03-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0018_products_tripday_products_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='GChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
                ('artistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.artist')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.user')),
            ],
        ),
    ]
