# Generated by Django 5.0.1 on 2024-03-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0022_alter_gchat_artistid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gchat',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gchat',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='gchat',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gchat',
            name='utype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
