# Generated by Django 5.0.1 on 2024-03-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0023_alter_gchat_date_alter_gchat_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gchat',
            name='packages',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
