# Generated by Django 5.0.1 on 2024-03-25 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0024_gchat_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gchat',
            name='packages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.products'),
        ),
    ]
