# Generated by Django 5.0.1 on 2024-03-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0025_alter_gchat_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gchat',
            name='artistid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.artist'),
        ),
        migrations.AlterField(
            model_name='gchat',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.user'),
        ),
    ]
