# Generated by Django 5.0.1 on 2024-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0026_alter_gchat_artistid_alter_gchat_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gchat',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
