# Generated by Django 5.0.1 on 2024-06-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0027_alter_gchat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completedpay',
            field=models.IntegerField(null=True),
        ),
    ]
