# Generated by Django 5.0.1 on 2024-10-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0028_cart_completedpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='proof',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
