# Generated by Django 5.2.11 on 2026-04-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0030_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
