# Generated by Django 5.2.11 on 2026-04-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0031_alter_cart_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CraftifyApp.artist'),
        ),
    ]
