# Generated by Django 5.2.11 on 2026-04-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftifyApp', '0032_notification_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
